version: '2'
services:
  cakephp_dockerized_mysql:
    container_name: cakephp_dockerized_mysql
    image: mysql:5.6
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cakephp_dockerized
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: 'unless-stopped'

  cakephp_dockerized:
    container_name: cakephp_dockerized
    image: img_cakephp_dockerized
    build: .
    ports:
      - 8081:80
    volumes:
      - ./web-app:/var/www/html
    links:
      - cakephp_dockerized_mysql
